In [1]:
!pip install spacy scikit-learn

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.11)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.21.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.2)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.1.4)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (8.3.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.1.0)

In [2]:
import spacy
import pandas as pd

from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score

In [3]:
nlp = spacy.load("en_core_web_sm")

In [4]:
data = [
    {
        "text": "Apple is planning to open a new office in Bengaluru next year.",
        "entities": [("Apple", "ORG"), ("Bengaluru", "GPE")]
    },
    {
        "text": "Elon Musk is the CEO of Tesla and SpaceX.",
        "entities": [("Elon Musk", "PERSON"), ("Tesla", "ORG"), ("SpaceX", "ORG")]
    },
    {
        "text": "Google announced a new AI research lab in London.",
        "entities": [("Google", "ORG"), ("London", "GPE")]
    },
    {
        "text": "Microsoft acquired LinkedIn for 26 billion dollars.",
        "entities": [("Microsoft", "ORG"), ("LinkedIn", "ORG")]
    },
    {
        "text": "Prime Minister Narendra Modi visited the United States.",
        "entities": [("Narendra Modi", "PERSON"), ("United States", "GPE")]
    },
    {
        "text": "Amazon has its headquarters in Seattle.",
        "entities": [("Amazon", "ORG"), ("Seattle", "GPE")]
    },
    {
        "text": "Meta launched a new feature on Instagram last week.",
        "entities": [("Meta", "ORG"), ("Instagram", "ORG")]
    },
    {
        "text": "The World Health Organization is based in Geneva.",
        "entities": [("World Health Organization", "ORG"), ("Geneva", "GPE")]
    },
    {
        "text": "Sundar Pichai spoke at the Google I/O event.",
        "entities": [("Sundar Pichai", "PERSON"), ("Google", "ORG")]
    },
    {
        "text": "India will host the G20 summit in New Delhi.",
        "entities": [("India", "GPE"), ("G20", "ORG"), ("New Delhi", "GPE")]
    }
]

df = pd.DataFrame(data)
df

,text,entities
0,Apple is planning to open a new office in Beng...,"[(Apple, ORG), (Bengaluru, GPE)]"
1,Elon Musk is the CEO of Tesla and SpaceX.,"[(Elon Musk, PERSON), (Tesla, ORG), (SpaceX, O..."
2,Google announced a new AI research lab in London.,"[(Google, ORG), (London, GPE)]"
3,Microsoft acquired LinkedIn for 26 billion dol...,"[(Microsoft, ORG), (LinkedIn, ORG)]"
4,Prime Minister Narendra Modi visited the Unite...,"[(Narendra Modi, PERSON), (United States, GPE)]"
5,Amazon has its headquarters in Seattle.,"[(Amazon, ORG), (Seattle, GPE)]"
6,Meta launched a new feature on Instagram last ...,"[(Meta, ORG), (Instagram, ORG)]"
7,The World Health Organization is based in Geneva.,"[(World Health Organization, ORG), (Geneva, GPE)]"
8,Sundar Pichai spoke at the Google I/O event.,"[(Sundar Pichai, PERSON), (Google, ORG)]"
9,India will host the G20 summit in New Delhi.,"[(India, GPE), (G20, ORG), (New Delhi, GPE)]"

In [5]:
def extract_entities(text):
    doc = nlp(text)
    return [(ent.text, ent.label_) for ent in doc.ents]

df["predicted_entities"] = df["text"].apply(extract_entities)
df

,text,entities,predicted_entities
0,Apple is planning to open a new office in Beng...,"[(Apple, ORG), (Bengaluru, GPE)]","[(Apple, ORG), (Bengaluru, GPE), (next year, D..."
1,Elon Musk is the CEO of Tesla and SpaceX.,"[(Elon Musk, PERSON), (Tesla, ORG), (SpaceX, O...","[(Elon Musk, PERSON), (Tesla, ORG)]"
2,Google announced a new AI research lab in London.,"[(Google, ORG), (London, GPE)]","[(Google, ORG), (AI, GPE), (London, GPE)]"
3,Microsoft acquired LinkedIn for 26 billion dol...,"[(Microsoft, ORG), (LinkedIn, ORG)]","[(Microsoft, ORG), (LinkedIn, ORG), (26 billio..."
4,Prime Minister Narendra Modi visited the Unite...,"[(Narendra Modi, PERSON), (United States, GPE)]","[(Narendra Modi, PERSON), (the United States, ..."
5,Amazon has its headquarters in Seattle.,"[(Amazon, ORG), (Seattle, GPE)]","[(Amazon, ORG), (Seattle, GPE)]"
6,Meta launched a new feature on Instagram last ...,"[(Meta, ORG), (Instagram, ORG)]","[(Meta, ORG), (Instagram, ORG), (last week, DA..."
7,The World Health Organization is based in Geneva.,"[(World Health Organization, ORG), (Geneva, GPE)]","[(The World Health Organization, ORG), (Geneva..."
8,Sundar Pichai spoke at the Google I/O event.,"[(Sundar Pichai, PERSON), (Google, ORG)]","[(Sundar Pichai, PERSON), (Google, ORG)]"
9,India will host the G20 summit in New Delhi.,"[(India, GPE), (G20, ORG), (New Delhi, GPE)]","[(India, GPE), (G20, ORG), (New Delhi, GPE)]"

In [6]:
true_labels = []
pred_labels = []

for i in range(len(df)):
    true = df.loc[i, "entities"]
    pred = df.loc[i, "predicted_entities"]

    true_dict = {text: label for text, label in true}
    pred_dict = {text: label for text, label in pred}

    for ent_text in true_dict:
        true_labels.append(true_dict[ent_text])
        pred_labels.append(pred_dict.get(ent_text, "O"))  # O = Not detected

In [7]:
accuracy = accuracy_score(true_labels, pred_labels)
precision = precision_score(true_labels, pred_labels, average='weighted', zero_division=0)
recall = recall_score(true_labels, pred_labels, average='weighted', zero_division=0)
f1 = f1_score(true_labels, pred_labels, average='weighted', zero_division=0)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

Accuracy : 0.8636363636363636
Precision: 1.0
Recall   : 0.8636363636363636
F1 Score : 0.9259376986649713

In [8]:
print(classification_report(true_labels, pred_labels, zero_division=0))

              precision    recall  f1-score   support

         GPE       1.00      0.86      0.92         7
           O       0.00      0.00      0.00         0
         ORG       1.00      0.83      0.91        12
      PERSON       1.00      1.00      1.00         3

    accuracy                           0.86        22
   macro avg       0.75      0.67      0.71        22
weighted avg       1.00      0.86      0.93        22

In [10]:
df.to_csv("ner_results.csv", index=False)
print("NER results saved successfully!")

NER results saved successfully!